version: '3.1'

services:
  postgres:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  apitest:
    build: .
    volumes:
      - ./src:/usr/app/src
      - ./test:/usr/app/test
    depends_on:
      - postgres
    environment:
      TEST_PG_URL: postgres://postgres:${PG_PASS}@postgres:5432
